apiVersion: v1
kind: Service
metadata:
  name: zabbix-agent2-service
  namespace: monitoring
spec:
  type: ClusterIP
  ports:
  - port: 10050
    targetPort: 10050
    protocol: TCP
  selector:
    app: zabbix
    component: agent2
