apiVersion: apps/v1
kind: Deployment
metadata:
  name: zabbix-agent2
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zabbix
      component: agent2
  template:
    metadata:
      labels:
        app: zabbix
        component: agent2
    spec:
      containers:
      - name: zabbix-agent2
        image: zabbix/zabbix-agent2:alpine-7.0.5
        ports:
        - containerPort: 10050
        env:
        - name: ZBX_SERVER_HOST
          value: "10.244.0.0/16,zabbix-server,zabbix-server-service"
        - name: ZBX_HOSTNAME
          value: "Zabbix server"
        - name: ZBX_METADATA
          value: "Linux Docker"
        - name: ZBX_PASSIVE_ALLOW
          value: "true"
        - name: ZBX_ACTIVE_ALLOW
          value: "true"
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
