apiVersion: v1
kind: Service
metadata:
  name: zabbix-server
  namespace: monitoring
spec:
  type: ClusterIP
  ports:
  - port: 10051
    targetPort: 10051
  selector:
    app: zabbix
    component: server
