apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-config
  namespace: monitoring
data:
  my.cnf: |
    [mysqld]
    log_bin_trust_function_creators = 1
    character-set-server = utf8mb4
    collation-server = utf8mb4_bin
    max_allowed_packet = 128M
    innodb_buffer_pool_size = 512M
