apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: zabbix-secret
  namespace: monitoring
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: zabbix-secret
    creationPolicy: Owner
  data:
  - secretKey: admin-password
    remoteRef:
      key: zabbix
      property: admin-password
  - secretKey: database-password
    remoteRef:
      key: zabbix
      property: database-password
  - secretKey: server-password
    remoteRef:
      key: zabbix
      property: server-password
  - secretKey: mysql-root-password
    remoteRef:
      key: mysql
      property: root-password
  - secretKey: mysql-zabbix-password
    remoteRef:
      key: mysql
      property: zabbix-password
